services:
  django-app:
    container_name: django
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: /bin/sh -c "python /app/test/manage.py migrate && gunicorn --chdir /app/test --bind 0.0.0.0:8000 --workers 4 --worker-class sync --reload test.wsgi:application"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - __pycache__/
            - env/
        - action: rebuild
          path: requirements.txt
  db:
    container_name: postgres
    image: postgres:18.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    container_name: redis
    image: redis:7.4-alpine
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASS}
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
    networks:
      - app-network
  celery:
    user: root
    container_name: celery
    build: 
      context: .
      dockerfile: dockerfiles/celery/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=test.settings
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
    depends_on:
      - django-app
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - app-network
  flower:
    container_name: flower
    build:
      context: .
      dockerfile: dockerfiles/flower/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: test.settings
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASS: ${REDIS_PASS}
      FLOWER_UNAUTHENTICATED_API: True
    depends_on:
      - celery
      - redis
    ports:
      - 5555:5555
    volumes:
      - .:/app
    networks:
      - app-network
networks:
  app-network:
volumes:
  pg-data:
  redis:
