# Generated by Django 6.0.4 on 2026-04-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_pccomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pccomp',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
