# Generated by Django 6.0.4 on 2026-04-13 10:13

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('members', '0004_pccomp_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
            ],
            options={
                'permissions': [('multiplication_access', 'Can access multiplication')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
