# Generated by Django 6.0.4 on 2026-04-13 10:13

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserPermissions",
            fields=[],
            options={
                "permissions": [("multiplication_access", "Can access multiplication")],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
