# Generated by Django 6.0.4 on 2026-04-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_userpermissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("inputs", models.CharField(max_length=255)),
                ("outputs", models.CharField(max_length=255)),
            ],
        ),
    ]
