# Generated by Django 6.0.4 on 2026-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="tools",
            name="tool_id",
            field=models.IntegerField(null=True),
        ),
    ]
