# Generated by Django 6.0.4 on 2026-04-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_tools_tool_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tools",
            name="tool_id",
            field=models.IntegerField(max_length=255),
        ),
    ]
