# Generated by Django 6.0.4 on 2026-04-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_alter_tools_tool_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tools",
            name="id",
        ),
        migrations.AlterField(
            model_name="tools",
            name="tool_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
